### ISSUE TITLE
Sql injection protection

### ISSUE THREAD

**Issue by JessWalters** [JessWalters/Vinny-Redux#20]
[//]: # (Please try to use this template, feel free to remove sections or add more you may think are relevant.)

## Feature Request or Issue?
Necessity.
## Overview
We currently have no filtering to stop sql injection attacks. FIX THIS

**Comment by JessWalters** [comment]
Clever use of prepared statements should stop this. I will test later and if a problem arises, reopen this.

**Comment by demisardonic** [comment]
It would be helpful if you could link the correcting PR on this closed issue.
