### ISSUE TITLE
Iso compliant 

### ISSUE THREAD

**Issue by quadespellman** [JessWalters/Vinny-Redux#37]
FEATURE

make vinny iso compliant. To become iso compliant look here https://qms-certification.com/how-to-get-iso-certification/?gclid=Cj0KCQiAoo7gBRDuARIsANeJKUb5nYwccT_MDDebDp2Mt6EdgVyEIimRD2bLdFIMfK1iSaiZY1qVTQ4aAr_bEALw_wcB

You need to be iso compliant for when you add loot boxes and multiplayer support.

**Comment by quadespellman** [comment]
Security says this is a p2 and should be categorized as such.

**Comment by JessWalters** [comment]
@quadespellman tell security that this is now labeled as p2
