### ISSUE TITLE
Commands only check beginning of command text

### ISSUE THREAD

**Issue by mickylindsay** [JessWalters/Vinny-Redux#39]
Commands only check the beginning of command text. Probable a `startsWith` check.
Proof 

![image](https://user-images.githubusercontent.com/12740851/49338336-578d6400-f5e5-11e8-81e6-dd5d7f71bc92.png)

**Comment by JessWalters** [comment]
@mickylindsay this is for the original vinny, this problem has been addressed in Vinny-redux.
